name = "qwik-chat"
workers_dev = true
deploy
compatibility_flags = [ "nodejs_compat" ]
[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "qwik-chat"
database_id = "e8329247-7a09-4ec3-bc20-5020c6c35a41"

[vars]
ENVIRONMENT = 'dev'
CUSTOM_HEADERS_TO_IGNORE = []

#
#Configuration for DEVELOPMENT environment
#
[env.staging]
name = "qwik-chat-dev"

[env.staging.vars]
ENVIRONMENT = 'staging'
CUSTOM_HEADERS_TO_IGNORE = []


#
#Configuration for PRODUCTION environment
#
[env.production]
name = "qwik-chat"
logpush=true

[env.production.vars]
ENVIRONMENT = 'production'
CUSTOM_HEADERS_TO_IGNORE = []

[placement]
mode = "smart"
