export default {
  icon: "i-simple-icons-goldenline",
  name: "零一万物",
  href: "https://platform.lingyiwanwu.com/apikeys",
  defaultModel: "yi-34b-chat-0205",
  models: [
    {
      value: "yi-large",
      label: "yi-large",
      input: 0.02,
      output: 0.02,
      context_length: 16000,
    },
    {
      value: "yi-large-turbo",
      label: "yi-large-turbo",
      input: 0.012,
      output: 0.012,
      context_length: 16000,
    },
    {
      value: "yi-large-rag",
      label: "yi-large-rag",
      input: 0.025,
      output: 0.025,
      context_length: 16000,
    },
    {
      value: "yi-medium",
      label: "yi-medium",
      input: 0.0025,
      output: 0.0025,
      context_length: 16000,
    },
    {
      value: "yi-medium-200k",
      label: "yi-medium-200k",
      input: 0.012,
      output: 0.012,
      context_length: 200000,
    },
    {
      value: "yi-spark",
      label: "yi-spark",
      input: 0.001,
      output: 0.001,
      context_length: 16000,
    },
    {
      value: "yi-vision",
      label: "yi-vision",
      input: 0.006,
      output: 0.006,
      context_length: 4000,
    },
  ],
  placeholder: "API Key",
};
