export default {
  icon: "i-simple-icons-openai",
  name: "硅基流动",
  href: "https://cloud.siliconflow.cn/account/ak",
  defaultModel: "internlm/internlm2_5-20b-chat",
  models: [
    {
      value: "internlm/internlm2_5-20b-chat",
      label: "internlm/internlm2_5-20b-chat",
      input: 0,
      output: 0,
      context_length: 32000,
    },
    {
      value: "Qwen/Qwen2-Math-72B-Instruct",
      label: "Qwen/Qwen2-Math-72B-Instruct",
      input: 0,
      output: 0,
      context_length: 32000,
    },
    {
      value: "meta-llama/Meta-Llama-3.1-405B-Instruct",
      label: "meta-llama/Meta-Llama-3.1-405B-Instruct",
      input: 0,
      output: 0,
      context_length: 32000,
    },
    {
      value: "meta-llama/Meta-Llama-3.1-70B-Instruct",
      label: "meta-llama/Meta-Llama-3.1-70B-Instruct",
      input: 0,
      output: 0,
      context_length: 32000,
    },
    {
      value: "meta-llama/Meta-Llama-3-70B-Instruct",
      label: "meta-llama/Meta-Llama-3-70B-Instruct",
      input: 0,
      output: 0,
      context_length: 32000,
    },
    {
      value: "meta-llama/Meta-Llama-3.1-8B-Instruct",
      label: "meta-llama/Meta-Llama-3.1-8B-Instruct",
      input: 0,
      output: 0,
      context_length: 32000,
    },
    {
      value: "Qwen/Qwen2-72B-Instruct",
      label: "Qwen/Qwen2-72B-Instruct",
      input: 0,
      output: 0,
      context_length: 32000,
    },
    {
      value: "THUDM/glm-4-9b-chat",
      label: "THUDM/glm-4-9b-chat",
      input: 0,
      output: 0,
      context_length: 32000,
    },
    {
      value: "deepseek-ai/DeepSeek-Coder-V2-Instruct",
      label: "deepseek-ai/DeepSeek-Coder-V2-Instruct",
      input: 0,
      output: 0,
      context_length: 32000,
    },
    {
      value: "deepseek-ai/DeepSeek-V2-Chat",
      label: "deepseek-ai/DeepSeek-V2-Chat",
      input: 0,
      output: 0,
      context_length: 32000,
    },
  ],
  placeholder: "API Key",
};
